import RPi.GPIO as GPIO
import time

MOTOR_FORWARD = 16
MOTOR_BACKWARDS = 20
GPIO.setmode(GPIO.BCM)
GPIO.setup(MOTOR_FORWARD, GPIO.OUT)
GPIO.setup(MOTOR_BACKWARDS, GPIO.OUT)

GPIO.output(MOTOR_BACKWARDS, GPIO.LOW)
GPIO.output(MOTOR_FORWARD, GPIO.HIGH)

time.sleep(20)

GPIO.output(MOTOR_FORWARD, GPIO.LOW)